drone-plugins/drone-meltwater-cache

- .drone.yml
- cache/cache.go
- cache/option.go
- cache/restorer.go
- internal/plugin/config.go
- internal/plugin/plugin.go
- main.go
- storage/backend/s3/s3_test.go
> Add support for erring out restore if key does not exist

- archive/tar/tar.go
- cache/restorer.go
> Fix paths for restore in windows

- .drone.yml
> update go version to 1.17.7

- .drone.yml
Fixes #
-
-
-
The automation suite for drone-meltwater-cache is passing successfully with the new updated images.
Reason for image update:
1. Security Reference Ticket - https://harness.atlassian.net/browse/SECAPP-258
2. To meet federal requirements for storing harness images.
> golang image upgrade to 1.18

- storage/backend/gcs/gcs.go
Fixes #
-
-
-
Skipping log print if jsonKey is not available for gcs.
> gcs log fix

- plugin.yml
> add plugin metadata [CI SKIP]

- archive/archive.go
- archive/gzip/gzip.go
- archive/gzip/gzip_test.go
- archive/tar/tar.go
- archive/tar/tar_test.go
- cache/rebuilder.go
> CI-6504: Add relative cache save and restore to drone plugin

- .drone.yml
> Publish assets on new release

- .drone.yml
- plugin.yml
> Release binary assets with compression

- .drone.yml
- .gitignore
- go.mod
- go.sum
> Fix cross compile build failure

- .drone.yml
> Update go version

- .drone.yml
- docker/Dockerfile.linux.amd64
- docker/Dockerfile.linux.arm64
- go.mod
> go version upgrade for CVE

- internal/plugin/autodetect/prepare_maven.go
> remove space from maven config

- .drone.yml
- go.mod
- go.sum
> [fix]: [ci-9254]: go version upgrade to 1.21

- docker/Dockerfile.linux.amd64
- docker/Dockerfile.linux.arm64
> [fix]: [CI-9254]: upgrade docker base image to 1.21 from 1.20

- docker/manifest.tmpl
> CI-9755 added win22 manifest

- main.go
- storage/backend/s3/s3.go
> feat: [CI-9882]: Removed private as Default value of ACL

- .drone.yml
> Updated the go version image to 1.21.5

- CHANGELOG.md
- README.md
- main.go
Fixes #70 
- Changed variable name for Azure config
> Fixed inputs for azure

- README.md
Fixes #
-
-
-
ACL default was long updated, removing it from readme too.
> Remove ACL default is private from README

- cache/cache.go
- cache/option.go
- cache/restorer.go
- internal/plugin/config.go
- internal/plugin/plugin.go
- main.go
> change the path separator default

- internal/gcp/tokenutil.go
- storage/backend/gcs/config.go
- storage/backend/gcs/gcs.go
Fixes #
-
-
-
Added the Support for OIDC-based Authentication for GCS.
I tested the change with the OIDC connector with my new change and current flow.
> feat: [CI-12042]: Add OIDC auth support

- cache/cache.go
- cache/restorer.go
- harness/client.go
- harness/http.go
- internal/plugin/plugin.go
- storage/backend/harness/harness.go
- storage/backend/harness/harness_test.go
> fix: [CI-12071]: implemented list API

- README.md
- git-hooks/.gitleaksignore
- git-hooks/README.md
- git-hooks/hooks/git-leaks-pre-commit.sh
- git-hooks/hooks/git-leaks.sh
- git-hooks/hooks/pre-commit
- git-hooks/hooks/pre-push
- git-hooks/install.sh
> feat: [CI-10849]: add git-leaks support

- harness/client.go
- harness/http.go
- storage/backend/harness/harness.go
- storage/backend/harness/harness_test.go
> fix: [CI-12935]: changed the impelmentation of list

- storage/backend/gcs/gcs.go
- storage/backend/gcs/gcs_test.go
- previously we used to find the keys only by matching the prefix, due to which it is matching more than one key from the bucket, hence giving the error as below. 
execution_link: https://qa.harness.io/ng/account/h61p38AZSV6MzEkpWWBtew/module/ci/orgs/default/projects/Abhay_Test/pipelines/CI12042/executions/f0EkHVY1T9KJm3HcSGIn5g/pipeline?storeType=INLINE
To fix this, I have added a check where instead of just matching the prefix, we are also matching the exact key name before pulling the data.
> fix: [CI-13141]: fix restore cache prefix matching

- .drone.yml
- DOCS.md
- README.md
- docs/examples/drone.md
> fix: [CI-13178]: Upgraded go version imaged to 1.22.4-alpine3.19

- storage/backend/gcs/gcs.go
- storage/backend/gcs/gcs_test.go
Fixes #
-
-
-
The recurring key issue was a known issue and its fix has been made under this PR, which was kept behind a flag
https://github.com/drone-plugins/drone-meltwater-cache/pull/96/files
Since this change was not documented nor was I informed about this when posted on the channel. missed this flag and made another fix for this issue.
I am reverting this change since this gets resolved when the added Stage flag is enabled.
> fix: [CI-13388]: revert recurring key fix

- .drone.yml
> Update git-secret in release binary step in .drone.yml

- archive/tar/tar.go
> fix: [CI-15249]: fixed bug where restore step failed on windows

- internal/plugin/autodetect/auto_detect_util.go
this plugin will now detect vbproj and fsproj files and cache dotnet dependencies
add code to detect vbproj and fsproj files
> feat: [CI-14396]: add support for vb, f# with .net 

- cache/cache.go
- cache/restorer.go
- internal/plugin/config.go
- internal/plugin/plugin.go
- main.go
Fixes #
-
-
-
Added support for writing cache size into a file that will be read by LE for telemetry purpose. 
This will read PLUGIN_CACHE_INTEL_FILE and write the content into that file
> feat: [CI-15661]: Add CacheMetadata file for telemetry

- internal/plugin/plugin.go
- internal/plugin/plugin_test.go
Updated terminating condition based on feedback
> fix: [CI-16616]: disable cache according to matrix

- plugin.yml
> [feat]: [CI-16417]: source fallback

- storage/backend/s3/s3.go
This PR improves the AWS credential and session management in the S3 backend by:
- Streamlining the session and credential management flow
- Adding proper session recreation with configured credentials
- Simplifying UserRoleArn handling with cleaner client creation
- Improving error handling for credential-based session creation
- Removing redundant code and comments
Testing:
- Before fix (execution with cache:1.9.6): [LINK](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/all/orgs/Ansibler/projects/Automate/pipelines/CI17095cacheplugincredentialsrefactor/executions/s5CJ-HtSRI-CZLjE5R4-Qg/pipeline?storeType=INLINE)
- After fix (execution with cache:1.9.7-debug): [LINK](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/all/orgs/Ansibler/projects/Automate/pipelines/CI17095cach …
> feat: [CI-17095]: refactor(s3): Improve AWS credential and session management flow

- internal/plugin/autodetect/auto_detect_util.go
- internal/plugin/autodetect/prepare_bzlmod.go
- internal/plugin/autodetect/prepare_bzlmod_test.go
> feat: [CI-18567]: support new version of bzlmod
